export const Tags = [
  { tag: 'The Shawshank Redemption' },
  { tag: 'The Godfather' },
  { tag: 'The Godfather: Part II'},
  { tag: 'The Dark Knight'},
  { tag: '12 Angry Men' },
  { tag: "Schindler's List"},
  { tag: 'Pulp Fiction'},
  {tag: 'The Lord of the Rings: The Return of the King'},
  { tag: 'The Good, the Bad and the Ugly', year: 1966 },
  { tag: 'Fight Club', year: 1999 },
  { tag: 'City of God'},
  { tag: 'Se7en' },
  { tag: 'The Silence of the Lambs'},
  { tag: "It's a Wonderful Life" },
  { tag: 'Life Is Beautiful'},
  { tag: 'The Usual Suspects'},
  { tag: 'Léon: The Professional' },
  { tag: 'Spirited Away' },
  { tag: 'Saving Private Ryan' },
  { tag: 'Once Upon a Time in the West' },
]
